import React from 'react';

export type LanguageType = 'vi' | 'en';

export const translations = {
  vi: {
    // Nav & General
    app_title: 'Quản lý công trình',
    warehouse: 'Kho vật tư',
    volume: 'Khối lượng',
    floorplan: 'Mặt bằng',
    checklist: 'Checklist',
    crew: 'Quân số',
    config: 'Cấu hình',
    search: 'Tìm kiếm...',
    add: 'Thêm mới',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    save: 'Lưu lại',
    cancel: 'Hủy',
    confirm: 'Xác nhận',
    export_excel: 'Xuất Excel',
    import_excel: 'Nhập Excel',
    all: 'Tất cả',
    
    // Config Tab
    config_title: 'Cấu hình',
    config_subtitle: 'Quản lý thông tin công trình & cài đặt chung',
    version: 'Phiên bản',
    project_settings: 'Thông Tin & Thiết Lập Công Trình',
    project_name: 'Tên Dự Án / Tòa Nhà',
    contractor: 'Đơn Vị Thi Công',
    inspector: 'Kỹ Sư Giám Sát',
    save_settings: 'Lưu Cài Đặt Dự Án Ngay',
    save_success: 'Đã cập nhật cấu hình hệ thống thành công!',
    formatting_settings: 'Cấu Hinh Định Dạng Số & Ngày Tháng',
    formatting_subtitle: 'Hiển Thị Cho Toàn App',
    number_format: 'Định Dạng Phân Cách Dấu Số',
    date_format: 'Định Dạng Hiển Thị Ngày Tháng Năm',
    language_settings: 'Cài Đặt Ngôn Ngữ Ứng Dụng',
    language_select: 'Chọn ngôn ngữ hiển thị',
    vietnamese: 'Tiếng Việt',
    english: 'English (Tiếng Anh)',
    language_applied: 'Đã chuyển đổi ngôn ngữ ứng dụng thành công!',
    daily_diary: 'Nhật Ký Hằng Ngày',
    team_directory: 'Mục Nhập Thông Tin Đội',
    norms_button: 'Định Mức',

    // Warehouse Tab
    warehouse_title: 'Danh Sách Kho Vật Tư',
    warehouse_subtitle: 'Báo cáo tồn kho & quản lý nhập xuất vật tư thực tế',
    total_stock: 'Tổng lượng vật tư tồn kho thực tế',
    add_material: 'Nhập Thêm Vật Tư',
    material_norms: 'Định Mức Vật Tư',
    material_name: 'Tên Vật Tư',
    category: 'Loại vật tư',
    import_qty: 'Số lượng nhập',
    unit: 'Đơn vị',
    last_update: 'Cập nhật cuối',
    actions: 'Thao tác',
    no_material: 'Không tìm thấy vật tư nào phù hợp',
    quick_sort: 'Sắp xếp nhanh',

    // Volume Tab
    volume_title: 'Khối Lượng Thi Công',
    volume_subtitle: 'Theo dõi & đối chiếu khối lượng thiết kế vs thực tế',
    add_volume: 'Thêm Hạng Mục Khối Lượng',
    planned_vol: 'KL Kế Hoạch',
    actual_vol: 'KL Thực Tế',
    progress: 'Tiến độ',
    no_volume: 'Chưa có hạng mục khối lượng nào phù hợp',
    sort_name: 'Tên Hạng Mục',
    sort_plan: 'KL Kế Hoạch',
    sort_progress: 'Tiến Độ %',

    // Floor Plan Tab
    floor_title: 'Mặt Bằng Thi Công',
    floorplan_title: 'Mặt Bằng Thi Công',
    floor_subtitle: 'Quản lý tiến độ hoàn thiện & ghi nhận defect theo vị trí',
    add_floor: 'Thêm Mặt Bằng Mới',
    apartments: 'Căn hộ',
    defects: 'Lỗi (Defect)',
    status_not_start: 'Chưa thi công',
    status_ongoing: 'Đang làm',
    status_done: 'Đã xong',
    status_inspected: 'Đã nghiệm thu',

    // Checklist Tab
    checklist_title: 'Checklist Nghiệm Thu',
    checklist_subtitle: 'Quản lý tiêu chí chất lượng cho từng phân khu',
    add_checklist: 'Thêm Tiêu Chí',
    status_passed: 'Đạt Nghiệm Thu',
    status_defect: 'Yêu Cầu Sửa',
    status_pending: 'Chờ Nghiệm Thu',

    // Crew Tab
    crew_title: 'Quản Lý Quân Số',
    crew_subtitle: 'Nhật ký nhân công & thống kê năng suất tổ đội',
    add_crew: 'Nhập Nhật Ký Quân Số',
    teams_list: 'Danh Sách Tổ Đội',
  },
  en: {
    // Nav & General
    app_title: 'Construction Management',
    warehouse: 'Warehouse',
    volume: 'Volumes',
    floorplan: 'Floor Plans',
    checklist: 'Checklist',
    crew: 'Crews',
    config: 'Settings',
    search: 'Search...',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    export_excel: 'Export Excel',
    import_excel: 'Import Excel',
    all: 'All',

    // Config Tab
    config_title: 'Configuration',
    config_subtitle: 'Manage project information & general settings',
    version: 'Version',
    project_settings: 'Project Information & Settings',
    project_name: 'Project Name / Building Name',
    contractor: 'Contractor',
    inspector: 'Inspector / Supervisor',
    save_settings: 'Save Project Settings Now',
    save_success: 'System configuration updated successfully!',
    formatting_settings: 'Number & Date Formatting Preferences',
    formatting_subtitle: 'Display settings for the entire app',
    number_format: 'Number Separation Format',
    date_format: 'Date Display Format',
    language_settings: 'Application Language Settings',
    language_select: 'Select display language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    language_applied: 'Application language updated successfully!',
    daily_diary: 'Daily Logs',
    team_directory: 'Crew Directory',
    norms_button: 'Norms',

    // Warehouse Tab
    warehouse_title: 'Material Inventory List',
    warehouse_subtitle: 'Inventory reports & actual material import/export management',
    total_stock: 'Total actual materials in stock',
    add_material: 'Import Materials',
    material_norms: 'Material Norms',
    material_name: 'Material Name',
    category: 'Material Category',
    import_qty: 'Import Qty',
    unit: 'Unit',
    last_update: 'Last updated',
    actions: 'Actions',
    no_material: 'No matching materials found',
    quick_sort: 'Quick Sort',

    // Volume Tab
    volume_title: 'Work Volume Tracking',
    volume_subtitle: 'Track and compare planned volume vs. actual work done',
    add_volume: 'Add Work Volume Item',
    planned_vol: 'Planned Vol',
    actual_vol: 'Actual Vol',
    progress: 'Progress',
    no_volume: 'No work volume items found',
    sort_name: 'Item Name',
    sort_plan: 'Planned Vol',
    sort_progress: 'Progress %',

    // Floor Plan Tab
    floor_title: 'Construction Floor Plans',
    floorplan_title: 'Construction Floor Plans',
    floor_subtitle: 'Manage completion progress & track defects by location',
    add_floor: 'Add New Floor Plan',
    apartments: 'Apartments',
    defects: 'Defects',
    status_not_start: 'Not Started',
    status_ongoing: 'Ongoing',
    status_done: 'Completed',
    status_inspected: 'Inspected',

    // Checklist Tab
    checklist_title: 'Acceptance Checklist',
    checklist_subtitle: 'Manage quality criteria for each subdivision',
    add_checklist: 'Add Criterion',
    status_passed: 'Passed Inspection',
    status_defect: 'Needs Revision',
    status_pending: 'Pending Inspection',

    // Crew Tab
    crew_title: 'Crew Count & Attendance',
    crew_subtitle: 'Labor journal & crew productivity statistics',
    add_crew: 'Log Labor Daily Attendance',
    teams_list: 'Teams & Crews List',
  }
};

export const getSavedLanguage = (): LanguageType => {
  if (typeof window !== 'undefined') {
    localStorage.removeItem('app_language');
  }
  return 'vi';
};

export const saveLanguageSetting = (_lang: LanguageType) => {
  // No-op, default is always Vietnamese
};

export const translateElement = (_element: Node) => {
  // No-op in default Vietnamese mode
};

// Global DOM Translation Map for Automatic Vietnamese to English fallback
// Sorted by phrase length (longest first) to prevent shorter sub-phrases from overriding larger ones!
export const directTranslations: Record<string, string> = {
  // Config / Setup preferences
  "Hàng nghìn: Dấu chấm (.) — Thập phân: Dấu phẩy (,)": "Thousands: dot (.) — Decimal: comma (,)",
  "Ví dụ: 1.234.567,85 (Chuẩn Việt Nam & Châu Âu)": "Example: 1.234.567,85 (Vietnam & Europe standard)",
  "Hàng nghìn: Dấu phẩy (,) — Thập phân: Dấu chấm (.)": "Thousands: comma (,) — Decimal: dot (.)",
  "Ví dụ: 1,234,567.85 (Chuẩn Mỹ & Quốc tế)": "Example: 1,234,567.85 (US & International standard)",
  "Cấu Hinh Định Dạng Số & Ngày Tháng": "Number & Date Formatting Preferences",
  "Cấu Hình Định Dạng Số & Ngày Tháng": "Number & Date Formatting Preferences",
  "Cài Đặt Tiến Độ Mục Tiêu Từng Tầng": "Target Progress Settings per Floor",
  "Cài Đặt Tiến Độ Mục Tiêu Từng FLOOR": "Target Progress Settings per Floor",
  "Tiêu chuẩn thi công & Kỹ sư giám sát:": "Construction Criteria & Supervisor:",
  "Tiêu chuẩn thi công & Kỹ sư giám sát: ": "Construction Criteria & Supervisor: ",
  "Quản lý thông tin công trình & cài đặt chung": "Manage project info & general configurations",
  "Thông Tin & Thiết Lập Công Trình": "Project Setup & Info",
  "Định Dạng Hiển Thị Ngày Tháng Năm": "Date Format Preference",
  "Định Dạng Phân Cách Dấu Số": "Number Delimiter Format",
  "Cài Đặt Ngôn Ngữ Ứng Dụng": "App Language Settings",
  "Chọn ngôn ngữ hiển thị": "Select Display Language",
  "Lưu Cài Đặt Dự Án Ngay": "Save Project Settings",
  "Lưu cài đặt dự án ngay": "Save Project Settings",
  "Cấu hình": "Settings",
  "Cấu Hình": "Settings",
  "Kỹ sư giám sát": "Supervisor",
  "Kỹ Sư Giám Sát": "Supervisor",
  "Đơn vị thi công": "Contractor",
  "Đơn Vị Thi Công": "Contractor",
  "Tên dự án": "Project Name",
  "Tên Dự Án": "Project Name",
  "Lưu cài đặt": "Save Settings",
  "Lưu Cài Đặt": "Save Settings",
  "Định dạng số": "Number Format",
  "Định dạng ngày": "Date Format",

  // Crew Attendance tab
  "PHÂN BỔ QUÂN SỐ THEO FLOOR LÀM VIỆC": "Crew Allocation by Active Floor",
  "PHÂN BỔ QUÂN SỐ THEO TẦNG LÀM VIỆC": "Crew Allocation by Active Floor",
  "Chọn Tất Cả Quân Số Ngày Này": "Select All Crews for Today",
  "TỔNG QUÂN SỐ HÔM NAY": "TOTAL CREWS TODAY",
  "Mục Nhập Thông Tin Đội": "Crew Directory",
  "Nhật Ký Hằng Ngày": "Daily Logs",
  "Mặt bằng khác": "Other area",
  "Mặt Bằng Khác": "Other area",
  "Trong đội:": "In crew:",
  "Trong đội": "In crew",
  "Ngoài đội:": "Outside crew:",
  "Ngoài đội": "Outside crew",
  "KHU VỰC LÀM NHIỀU": "MOST ACTIVE AREA",
  "Khu Vực Làm Nhiều": "Most Active Area",
  "Tập trung 10 thợ": "Focusing on 10 workers",
  "Ghi nhận quân số": "Log Crew",
  "Sao chép hôm qua": "Copy Yesterday",
  "NHẬT KÝ LÀM VIỆC": "WORK JOURNAL",
  "Nhật Ký Làm Việc": "Work Journal",
  "Xóa Tất Cả": "Delete All",
  "Danh Sách Tổ Đội": "Crew & Teams List",
  "Quản Lý Nhân Công": "Crew Attendance",
  "Quân Số Định Biên Mặc Định": "Default Allocation",
  "Đội trưởng:": "Crew Leader:",
  "Đội Trưởng:": "Crew Leader:",
  "Đội trưởng": "Crew Leader",
  "SĐT:": "Phone:",
  "SĐT": "Phone",
  "Để gán đội thi công cho từng căn hộ / phòng, bạn hãy vào tab \"Sơ đồ mặt bằng\", chọn vùng phòng cần giao và chọn đội": "To assign a crew to a specific room, go to the \"Floor Plans\" tab, select the room area, and choose the crew",
  "Không có lỗi defect nào cần khắc phục!": "No defects need to be fixed!",
  "Không tìm thấy defect nào theo bộ lọc": "No defects found with current filters",
  "Tổng quân số hôm nay (Người)": "Total crews today (People)",
  "Tổng Công Trong Đội (Công)": "Total Crew Work Days",
  "Tổng Công Ngoài Đội (Công)": "Total Sub-contracted Work Days",
  "Tổng Công Thực Hiện (Công)": "Total Execution Work Days",
  "Đội Trưởng": "Crew Leader",
  "Trưởng đội": "Crew Leader",
  "Trưởng Nhóm": "Group Leader",
  "Trưởng Nhóm / Đội Trưởng": "Group Leader / Crew Leader",
  "Nhật ký": "Attendance Logs",
  "Nhật ký làm việc": "Work Journal",
  "Thành viên": "Members",
  "Thành viên đội": "Crew Members",
  "Quản lý nhân công": "Labor Management",
  "Thêm Đội Thi Công Mới": "Add New Construction Crew",
  "Sửa Thông Tin Đội": "Edit Crew Info",
  "Tên đội thi công": "Crew name",
  "Vui lòng nhập tên đội thi công!": "Please enter the crew name!",
  "Vui lòng nhập tên đội trưởng!": "Please enter the crew leader's name!",
  "Vui lòng nhập số điện thoại hợp lệ!": "Please enter a valid phone number!",
  "Mô tả đội thi công": "Crew description",
  "Bản ghi quân số": "Crew attendance record",
  "Đã xóa bản ghi quân số thành công!": "Deleted crew attendance record successfully!",
  "Nhập nhật ký quân số": "Log Daily Crew Attendance",
  "Chọn ngày ghi nhận": "Select logging date",
  "Chọn mặt bằng làm việc": "Select floor plan location",
  "Số thợ trong đội": "Regular crew workers",
  "Số thợ ngoài đội": "Sub-contracted workers",
  "Nhập số công chi tiết...": "Enter detailed work days...",
  "Mô tả công việc hôm nay": "Work done description today",
  "Ghi nhận quân số hôm nay thành công!": "Crew logged successfully today!",
  "Sao chép dữ liệu từ hôm qua thành công!": "Copied data from yesterday successfully!",
  "Không tìm thấy dữ liệu quân số hôm qua để sao chép!": "No crew logs found for yesterday to copy!",

  // Checklist tab
  "Chua co tieu chi Checklists nao cho": "No checklists found for",
  "Chưa có tiêu chí Checklists nào cho": "No checklists found for",
  "Chưa có tiêu chí Checklist nào cho": "No checklists found for",
  "Bấm \"Thêm Tiêu Chí\" hoặc \"Import Excel\" để bắt đầu.": "Click \"Add Criterion\" or \"Import Excel\" to begin.",
  "Bấm \"Thêm Tiêu Chí\" hoặc \"Nhập Excel\" để bắt đầu.": "Click \"Add Criterion\" or \"Import Excel\" to begin.",
  "Chờ Nghiệm Thu": "Pending Inspection",
  "Trạng Thái Nghiệm Thu": "Inspection Status",
  "Nội Dung Tiêu Chí": "Checklist Content",
  "Yêu Cầu Sửa": "Needs Revision",
  "Sắp xếp nhanh:": "Quick Sort:",
  "Sắp xếp nhanh": "Quick Sort",
  "Thời Hạn": "Due Date",
  "Tải Mẫu Excel": "Export Template",
  "Nhập Excel": "Import Excel",
  "Tải mẫu Excel hoặc danh sách checklist hiện tại để chỉnh sửa": "Download Excel template or current checklists to edit",
  "Chọn Tất Cả Trên Trang": "Select All on Page",
  "Xóa Đã Chọn": "Delete Selected",
  "Đạt Nghiệm Thu": "Passed Acceptance",
  "Chỉnh Sửa Tiêu Chí Checklist": "Edit Checklist Criterion",
  "Nội Dung Tiêu Chuẩn": "Standard Checklist Content",
  "Hạng Mục Kiểm Tra": "Inspection Item",
  "Vị Trí (Tầng)": "Location (Floor)",
  "Kiểm tra kỹ khoảng cách ty treo": "Carefully check hanger wire spacing",
  "Khoảng cách giữa các thanh xương chính tuân thủ thiết kế (800-1000mm)": "Primary channel spacing complies with design (800-1000mm)",
  "Thi công bắn tấm trần": "Drywall ceiling boarding",
  "Thi công khung trần": "Suspended ceiling framing",
  "Sơn bả & Hoàn thiện": "Painting & Finishing",

  // Floor Plans detailed view
  "Chưa có phòng / căn hộ nào trên Floor Plans này. Hãy dùng công cụ vẽ để tạo vùng highlight!": "No rooms/apartments on this Floor Plan. Please use the drawing tool to create highlight areas!",
  "Chưa có phòng / căn hộ nào trên Floor Plans này.": "No rooms/apartments on this Floor Plan.",
  "Hãy dùng công cụ vẽ để tạo vùng highlight!": "Please use the drawing tool to create highlight areas!",
  "Chưa có lỗi defect nào được ghi nhận trên Floor Plans này 🎉": "No defects recorded on this Floor Plan 🎉",
  "NGHIỆM THU TỪNG CĂN HỘ / PHÒNG": "ACCEPTANCE BY APARTMENT / ROOM",
  "Đạt Cả Khung & Tấm:": "Passed Frame & Board:",
  "Thi công xong:": "Completed:",
  "Bắn tấm xong:": "Board installed:",
  "Thi công xong": "Completed",
  "Bắn tấm xong": "Board installed",
  "Đạt NT Khung:": "Passed Frame Inspection:",
  "Đạt NT Tấm:": "Passed Board Inspection:",
  "NT HOÀN THIỆN": "FINAL INSPECTION",
  "NT Hoàn Thiện": "Final Inspection",
  "DANH SÁCH LỖI DEFECT": "DEFECT LIST",
  "Danh Sách Lỗi Defect": "Defect List",
  "Trần chìm chống ẩm": "Moisture-resistant ceiling",
  "Thêm Căn Hộ": "Add Apartment",
  "Bản Đồ Mặt Bằng": "Floor Plan Map",
  "Cập Nhật Trạng Thái": "Update Status",
  "Nhật Ký Hoạt Động": "Activity History",
  "Căn hộ thi công": "Apartments in progress",
  "Bản Vẽ Tổng Hợp": "Master Plan",
  "Cập Nhật Bản Vẽ": "Update Drawing",
  "Mỗi Căn 1 Màu": "Color code per room",
  "Chỉ Hiện Màu": "Show color only",
  "Bản Vẽ Tổng Hợp ": "Master Layout Drawing",
  "Căn hộ thi công ": "Apartments in Progress",
  "DANH SÁCH FLOOR Project:": "Project Floor List:",
  "DANH SÁCH TẦNG Dự Án:": "Project Floor List:",
  "Xem Tổng Hợp Tất Cả": "View Summary of All",
  "Tùy Chỉnh FLOOR": "Customize Floors",
  "Tùy Chỉnh Tầng": "Customize Floors",
  "Vẽ Tự Do": "Free Draw",
  "Vẽ Đa Giác": "Polygon Draw",
  "Vẽ Chữ Nhật": "Rectangle Draw",
  "Mặt bằng Highlight Căn Hộ": "Apartment Highlights",
  "Mặt bằng Defect & Highlight": "Defect & Highlight Map",
  "Tải báo cáo Excel thống kê chi tiết cho đội thi công này": "Export detailed Excel report for this crew",
  "Bấm trực tiếp vào các ghim đỏ/vàng trên hình để xem ảnh & chi tiết lỗi.": "Click directly on the red/yellow pins on the image to view photos & defect details.",
  "Ảnh Báo Lỗi Ban Đầu (Trước Sửa)": "Initial Defect Photo (Before Repair)",
  "Ảnh lỗi phát hiện (Trước)": "Defect Detected Photo (Before)",
  "Ảnh lỗi khắc phục (Sau)": "Defect Resolved Photo (After)",
  "Ảnh lỗi khắc phục (Sau) (Tùy Chọn)": "Resolution Photo (After) (Optional)",
  "Ảnh Sau Khi Sửa": "Photo After Repair",
  "Ảnh Trước Khi Sửa": "Photo Before Repair",
  "Ảnh sau sửa": "Photo after repair",
  "Ảnh trước sửa": "Photo before repair",
  "Ảnh sơ đồ mặt bằng": "Floor plan drawing",
  "Thêm mới mặt bằng nhanh": "Quick Add Floor",
  "Nhập tên tầng mới...": "Enter new floor name...",
  "Bấm 2 điểm đối góc để tạo khung hình chữ nhật": "Click 2 diagonal points to create a rectangle frame",
  "Bấm 2 điểm đối góc trên mặt bằng để vẽ khung hình chữ nhật!": "Click 2 diagonal points on the floor plan to draw a rectangle!",
  "Bấm 2 điểm tạo khung chữ nhật": "Click 2 points to draw rectangle",
  "Vẽ tự do bằng cách nhấn giữ và kéo chuột/tay trên mặt bằng": "Free draw by clicking & dragging on the floor plan",
  "Xóa căn hộ / vùng highlight này": "Delete this apartment / highlight area",
  "Xóa căn này": "Delete this unit",
  "Xóa tầng này": "Delete this floor",
  "Xoá tầng này": "Delete this floor",
  "Xác nhận xóa": "Confirm Delete",
  "Bạn có chắc chắn muốn xóa mặt bằng": "Are you sure you want to delete floor plan",
  "Không thể xóa mặt bằng duy nhất!": "Cannot delete the only floor plan!",
  "Bạn có chắc chắn muốn xóa phòng": "Are you sure you want to delete room",
  "Báo lỗi defect": "Report Defect",
  "Vui lòng nhập tên phòng hoặc mã căn hộ!": "Please enter the room name or unit code!",
  "Vui lòng chọn hoặc nhập tên đội thi công!": "Please select or enter the crew name!",
  "Vui lòng nhập tên trưởng nhóm/đội trưởng!": "Please enter the crew leader's name!",
  "Vui lòng chọn ít nhất một hạng mục thi công liên kết!": "Please select at least one linked construction item!",
  "Mức độ nghiêm trọng": "Severity Level",
  "Trạng thái lỗi": "Defect Status",
  "Người chịu trách nhiệm": "Responsible party",
  "Đội thạch cao": "Drywall Crew",
  "Lỗi thi công": "Construction Defect",
  "Chi tiết lỗi": "Defect Details",
  "Nhấn vào hình để xem ảnh phóng to": "Click on image to view full size",
  "Tải tệp vẽ": "Upload drawing file",
  "Hỗ trợ ảnh JPG/PNG hoặc tài liệu PDF...": "Supports JPG/PNG or PDF documents...",
  "Kéo thả tệp bản vẽ vào đây": "Drag and drop drawing file here",
  "hoặc Bấm để chọn tệp từ máy tính": "or click to browse files",
  "Đang nạp file... Please wait...": "Loading file... Please wait...",
  "Cập nhật bản vẽ thành công!": "Updated drawing successfully!",
  "Đã cập nhật lỗi thành công!": "Defect updated successfully!",
  "Xóa lỗi thành công!": "Defect deleted successfully!",
  "Bạn có chắc muốn xóa lỗi này?": "Are you sure you want to delete this defect?",
  "Không có lỗi defect nào được ghi nhận trên mặt bằng này 🎉": "No defects recorded on this floor plan 🎉",
  "Vị trí defect": "Defect Location",
  "Mô tả lỗi": "Defect Description",
  "Hạng mục liên kết": "Linked Item",
  "Vách thạch cao": "Drywall partition wall",
  "Đạt Cả Khung & Tấm": "Passed Frame & Board",
  "Bắn Tấm": "Boarding",
  "Bắn tấm": "Boarding",
  "Khung Xương": "Framing",
  "Khung xương": "Framing",
  "Xong Bắn Tấm": "Boarding Completed",
  "Xong Khung Xương": "Framing Completed",
  "CĂN HỘ / PHÒNG": "APARTMENT / ROOM",
  "Đội Thi Công": "Active Crew",
  "Trưởng Đội": "Crew Leader",
  "Mức Độ": "Severity",
  "Mô Tả Lỗi": "Description",
  "Hình Ảnh": "Photos",
  "Không có lỗi": "No defects",
  "Chọn tệp tin trước sửa": "Select photo before repair",
  "Chọn tệp tin sau sửa": "Select photo after repair",
  "Đang xử lý ảnh...": "Processing image...",

  // Work Volume tab
  "Tổng Giá Trị & Tiến Độ Sản Lượng": "Total Value & Production Progress",
  "Đã Thực Hiện (Nghiệm thu)": "Completed (Inspected)",
  "Giá Trị Định Mức": "Norm Value",
  "Hoàn Thành": "Completed",
  "Tên Hạng Mục": "Item Name",
  "KL Kế Hoạch": "Planned Qty",
  "KL Thực Tế": "Actual Qty",
  "Tiến Độ %": "Progress %",
  "Tên Item": "Item Name",
  "Planned Qty": "Planned Qty",
  "Hạng mục": "Item",
  "Hạng Mục": "Item",
  "Hạng mục con:": "Sub-items:",
  "Hạng mục con": "Sub-items",
  "Chủng Loại": "Category",
  "Phân Loại": "Category",
  "Đơn Giá (VNĐ)": "Unit Price (VND)",
  "Sảnh / Ngoại thất": "Lobby / Exterior",
  "Thi công cách âm / bảo ôn bông thủy tinh": "Soundproofing / Fiberglass Insulation",
  "Thi công trần giật cấp nghệ thuật": "Artistic Coffered Ceiling",
  "Bả matit 2 lớp": "2-coat Plastering",
  "Bả matit lớp 1": "1st-coat Plastering",
  "Bả matit lớp 2": "2nd-coat Plastering",
  "Trét mối nối & dán băng keo thủy tinh": "Joint tape & fiberglass mesh",
  "Trét mối nối & dán keo lưới chống nứt": "Joint compound & anti-crack tape",
  "Xử lý khe nối tấm thạch cao & băng keo dán mối nối": "Joint treatment & joint tape",
  "Xử lý mối nối bột trét & dán băng keo lưới": "Joint plastering & fiberglass tape",
  "Vệ sinh mặt bằng & tập kết vật tư": "Site cleanup & material staging",
  "Thu dọn phế thải thạch cao tấm vụn": "Drywall scrap cleanup",

  // Warehouse Tab
  "Bảng Tổng Tồn Kho vs Định Mức": "Summary of Stock vs. Norms",
  "Nhập Thêm Vật Tư": "Import Materials",
  "Định Mức Vật Tư": "Material Norms",
  "HẾT HÀNG": "OUT OF STOCK",
  "TỔNG TỒN KHO": "TOTAL STOCK",
  "Tên Vật Tư": "Material Name",
  "Loại vật tư": "Material Category",
  "Số lượng nhập": "Import Qty",
  "Chủng loại": "Category",
  "Đơn vị": "Unit",
  "Số lượng": "Quantity",
  "Vị trí": "Location",
  "Cập nhật cuối": "Last updated",
  "Thao tác": "Actions",
  "Không tìm thấy vật tư nào phù hợp": "No matching materials found",
  "Tổng lượng vật tư tồn kho thực tế": "Total actual materials in stock",
  "Phiếu Nhập/Xuất Kho": "Inventory In/Out Ticket",
  "Nhập Số Lượng": "Import Qty",
  "Xuất Số Lượng": "Export Qty",
  "Mã Phiếu": "Ticket ID",
  "Loại Phiếu": "Ticket Type",
  "Người Thực Hiện": "Handler",
  "Ngày Thực Hiện": "Execution Date",
  "Ghi Chú": "Notes",
  "Xem định mức vật tư": "View Material Norms",
  "Cập nhật chủng loại vật tư, ĐVT, định mức": "Update categories, units, norms",
  "Vui lòng nhập tên vật tư và số lượng hợp lệ!": "Please enter a valid material name and quantity!",
  "Đã thêm phiếu NHẬP KHO thành công!": "Material IMPORT ticket added successfully!",
  "Đã thêm phiếu XUẤT KHO thành công!": "Material EXPORT ticket added successfully!",
  "Chọn Phạm Vi Lưu & Định Mức": "Select Storage & Norms",
  "Học định mức từ hạng mục khối lượng...": "Learn norms from work volume items...",
  "NHẬP KHO": "INVENTORY IMPORT",
  "XUẤT KHO": "INVENTORY EXPORT",
  "Vật tư thạch cao": "Drywall Materials",
  "Vật tư tồn kho": "Materials In Stock",
  "Nhập kho": "Import",
  "Xuất kho": "Export",
  "Tồn kho": "In Stock",
  "Tồn Kho Thực Tế": "Actual Stock",
  "Hao phí định mức": "Norm wastage",
  "Định Mức Hao Phí / m2": "Unit Norm / m2",
  "Định mức tiêu hao": "Consumption Norm",
  "Số Lượng Định Mức": "Norm Qty",
  "Định Mức / m2": "Norm / m2",
  "Thép mạ kẽm dày 0.4mm": "Galvanized steel 0.4mm",
  "Keo bọt nở": "Expanding foam",
  "Đen âm trần 12W": "12W Recessed Light",
  "Báo cáo tồn kho": "Inventory Report",

  // Common UI words
  "Đạt NT": "Passed",
  "Chưa NT": "Pending",
  "Đạt": "Passed",
  "Lỗi": "Defect",
  "Chờ": "Pending",
  "Tầng 1": "Floor 1",
  "Tầng 2": "Floor 2",
  "Tầng 3": "Floor 3",
  "Tầng 4": "Floor 4",
  "Tầng 5": "Floor 5",
  "Tầng 6": "Floor 6",
  "Tầng": "Floor",
  "tầng": "floor",
  "TẦNG": "FLOOR",
  "Căn hộ": "Apartment",
  "Căn": "Unit",
  "căn": "unit",
  "CĂN": "UNIT",
  "Thêm mới": "Add New",
  "Chỉnh sửa": "Edit",
  "Xóa": "Delete",
  "Lưu lại": "Save",
  "Hủy": "Cancel",
  "Xác nhận": "Confirm",
  "Tất cả": "All",
  "Thống kê": "Statistics",
  "THỐNG KÊ THI CÔNG": "CONSTRUCTION STATISTICS",
  "DEFECT TỒN ĐỘNG": "PENDING DEFECTS",
  "TỔNG CÔNG ĐÃ LÀM": "TOTAL WORK DAYS",
  "Tổng KL:": "Total Vol:",
  "Tổng KL": "Total Vol",
  "Người thực hiện": "Handler",
  "Ngày thực hiện": "Date",
  "Kế hoạch": "Plan",
  "Thực tế": "Actual",
  "Tiến độ": "Progress",
  "Tìm kiếm": "Search",
  "Thông tin": "Information",
  "Ngôn ngữ": "Language",
  "Tiếng Việt": "Vietnamese",
  "Tiếng Anh": "English",
  "Định mức": "Norms",
  "Tình Trạng": "Status",
  "Đã thêm mới": "Added",
  "Đã xóa": "Deleted",
  "Đã cập nhật": "Updated",
  "Báo cáo tổng hợp": "Summary Report",
  "Nhập file Excel": "Import Excel File",
  "Xuất file Excel": "Export Excel File",
  "Đang xem:": "Viewing:",
  "lỗi": "defects",
  "tổng defect": "total defects",
  "Chọn Tất Cả": "Select All",
  "Bỏ Chọn Tất Cả": "Deselect All",
  "Đang tải dữ liệu...": "Loading data...",
  "Hệ thống đang đồng bộ...": "System syncing...",
  "Không có dữ liệu": "No data available",
  "Chưa có bản ghi nào": "No records found",
  "Sao lưu dữ liệu": "Backup Data",
  "Khôi phục dữ liệu": "Restore Data",
  "Lịch sử hoạt động": "Activity Logs",
  "Xóa sạch dữ liệu": "Reset All Data",
  "Trung Tâm Lưu & Đồng Bộ Dự Án": "Project Sync & Backup Center",
  "Lưu Trữ Thiết Bị & Cloud": "Local & Cloud Storage",
  "Đồng Bộ Google Sheets": "Sync Google Sheets",
  "Sao Lưu & Khôi Phục": "Backup & Restore",
  "Khôi Phục Bản Sao Lưu": "Restore Backup",
  "Phiên bản sao lưu": "Backup Version",
  "Xác nhận khôi phục": "Confirm Restore",
  "Vui lòng nhập tên dự án hợp lệ!": "Please enter a valid project name!",

  // Placeholders
  "Tìm kiếm công việc, tầng, hạng mục...": "Search tasks, floors, items...",
  "Tìm kiếm dự án...": "Search projects...",
  "Tìm tên vật tư, chủng loại, ĐVT...": "Search material name, category, unit...",
  "Tìm vật tư, vị trí kho, người giao...": "Search materials, warehouse location, handler...",
  "Tìm vị trí, vật tư...": "Search location, materials...",
  "Tìm kiếm...": "Search...",
  "Nhập tên vật tư...": "Enter material name...",
  "Nhập số lượng...": "Enter quantity...",
  "Ví dụ: Tấm": "e.g., Sheet",
  "Ví dụ: Đèn âm trần 12W, Keo bọt nở...": "e.g., 12W Recessed Light, Expanding Foam...",
  "Ghi chú xuất cho tổ đội nào, hóa đơn đi kèm...": "Notes on which team issued, invoices...",
  "Ví dụ: Thi công khung trần chìm Tầng 3": "e.g., Suspended drywall ceiling Floor 3",
  "Nhập hoặc chọn nhóm": "Enter or select group",
  "Ví dụ: m2": "e.g., m2",
  "Ví dụ: Đội Thạch Cao Hà Nội...": "e.g., Hanoi Drywall Crew...",
  "Ví dụ: Đội trưởng Hùng, Anh Tiến...": "e.g., Crew Leader Hung, Mr. Tien...",
  "Ví dụ: Đội trưởng Hùng, Anh Cường...": "e.g., Crew Leader Hung, Mr. Cuong...",
  "Ví dụ: 0912345678": "e.g., 0912345678",
  "Ví dụ: Đội chuyên thạch cao trần giật cấp, khoán khối lượng...": "e.g., Specialized in suspended ceilings...",
  "Ví dụ: Đã nhận đủ vật tư, tăng ca hoàn thành trần phòng A102...": "e.g., Received all boards, worked overtime to complete ceiling A102...",
  "Ví dụ: Bắn thiếu vít khoảng cách >30cm, khung trần bị võng 10mm...": "e.g., Screws missing spacing >30cm...",
  "Ví dụ: Bắn vít khoảng cách 20cm, không chồi đầu vít...": "e.g., Screw spacing 20cm, no protruding screw heads...",
  "Tên kỹ sư giám sát...": "Supervisor name...",
  "Ghi chú cụ thể...": "Specific notes...",
  "Mới phát hiện": "Newly detected",
  "Đang sửa": "Under repair",
  "Đã khắc phục": "Resolved",
  "Đạt nghiệm thu": "Inspected & Passed",
  "Nghiêm trọng": "High",
  "Trung bình": "Medium",
  "Thấp": "Low",

  // Alerts & Dialogs
  "Bạn có chắc chắn muốn xóa dự án này? Toàn bộ dữ liệu của dự án trên máy sẽ bị xóa vĩnh viễn.": "Are you sure you want to delete this project? All local data will be permanently deleted.",
  "Hành động này không thể hoàn tác.": "This action cannot be undone.",
  "Vui lòng điền đầy đủ thông tin!": "Please fill in all information!",
  "Xóa thành công!": "Deleted successfully!",
  "Cập nhật thành công!": "Updated successfully!",
  "Thêm mới thành công!": "Added successfully!",

};

export const translateTextNodeValue = (text: string): string => {
  const trimmed = text.trim();
  if (!trimmed) return text;

  // 1. Direct exact phrase translations (high priority)
  if (directTranslations[trimmed]) {
    return directTranslations[trimmed];
  }

  let result = text;

  // 2. Specific dynamic text pattern replacements
  result = result.replace(/(\d+)\s*căn\b/gi, '$1 units');
  result = result.replace(/(\d+)\s*tầng\b/gi, '$1 floors');
  result = result.replace(/(\d+)\s*lỗi\b/gi, '$1 defects');
  result = result.replace(/(\d+)\s*công\b/gi, '$1 work days');
  result = result.replace(/(\d+)\s*lượt nhật ký\b/gi, '$1 log entries');
  result = result.replace(/(\d+)\s*thợ\b/gi, '$1 workers');
  result = result.replace(/(\d+)\s*người\b/gi, '$1 people');
  result = result.replace(/Định biên:\s*(\d+)\s*thợ/gi, 'Norm: $1 workers');
  result = result.replace(/Đội trưởng:\s*/gi, 'Crew Leader: ');
  result = result.replace(/SĐT:\s*/gi, 'Phone: ');
  result = result.replace(/NT:\s*/gi, 'Passed: ');
  result = result.replace(/Tổng KL:\s*/gi, 'Total Vol: ');

  // 3. Precise substring replacement of key phrases (ordered from longest keys first)
  // We use word boundaries safely but only on keys longer than 4 chars to avoid breaking standard words like "công".
  const sortedKeys = Object.keys(directTranslations).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (key.length > 4) {
      const val = directTranslations[key];
      // Escape special characters for regex
      const escapedKey = key.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      // Case-sensitive exact substring search
      const regex = new RegExp(escapedKey, 'g');
      result = result.replace(regex, val);
    }
  }

  // Handle specific single word boundary replacements safely
  // E.g., standalone Tầng or TẦNG
  result = result.replace(/\bTầng\b/g, 'Floor');
  result = result.replace(/\btầng\b/g, 'floor');
  result = result.replace(/\bTẦNG\b/g, 'FLOOR');
  result = result.replace(/\bCăn hộ\b/g, 'Apartment');
  result = result.replace(/\bcăn hộ\b/g, 'apartment');
  result = result.replace(/\bCăn\b/g, 'Unit');
  result = result.replace(/\bcăn\b/g, 'unit');

  return result;
};

const isExcluded = (element: Element | null): boolean => {
  if (!element) return false;
  const tagName = element.tagName.toUpperCase();
  if (tagName === 'SCRIPT' || tagName === 'STYLE' || tagName === 'TEXTAREA' || tagName === 'INPUT') return true;
  if (element.closest && element.closest('[data-i18n-skip="true"], [data-user-content="true"], .no-i18n')) {
    return true;
  }
  return false;
};


