import assert from 'node:assert/strict';
import fs from 'node:fs';
import { getHnlPrimaryThemeColors, hnlContrastRatio } from '../src/utils/hnlPrimaryTheme.ts';
const base = new URL('../', import.meta.url);
const css = fs.readFileSync(new URL('src/index.css', base), 'utf8');
const app = fs.readFileSync(new URL('src/App.tsx', base), 'utf8');
const nav = fs.readFileSync(new URL('src/components/BottomNav.tsx', base), 'utf8');
const admin = fs.readFileSync(new URL('src/components/SuperAdminCenter.tsx', base), 'utf8');
const home = fs.readFileSync(new URL('src/components/HomeDashboard.tsx', base), 'utf8');
const settings = fs.readFileSync(new URL('src/components/GoogleConfigTab.tsx', base), 'utf8');
assert.equal(getHnlPrimaryThemeColors('#2563eb').hover, '#1d4ed8');
const html = fs.readFileSync(new URL('index.html', base), 'utf8');
const manifest = JSON.parse(fs.readFileSync(new URL('public/manifest.json', base), 'utf8'));
assert.match(html, /name="theme-color" content="#2563eb"/);
assert.equal(manifest.theme_color, '#2563eb');
assert.match(app, /setAttribute\('content', hnlPalette\.action\)/);
assert.ok(!html.includes('name="theme-color" content="#4f46e5"'));
for (const primary of ['#2563eb', '#9333ea', '#facc15', '#ffffff', '#000000', '#00ff00']) {
  const palette = getHnlPrimaryThemeColors(primary);
  assert.ok(hnlContrastRatio(palette.action, '#ffffff') >= 4.5, `button contrast ${primary}`);
  assert.ok(hnlContrastRatio(palette.lightText, '#ffffff') >= 4.5, `light text ${primary}`);
  assert.ok(hnlContrastRatio(palette.darkText, '#0f172a') >= 4.5, `dark text ${primary}`);
  console.log(`${primary}: action=${palette.action}, darkText=${palette.darkText}, light=${hnlContrastRatio(palette.lightText, '#ffffff').toFixed(2)}, dark=${hnlContrastRatio(palette.darkText, '#0f172a').toFixed(2)}`);
}
assert.match(css, /html\[data-hnl-theme="dark"\] \.text-indigo-600/);
assert.match(css, /\[data-hnl-nav-surface\] \.bg-blue-50/);
assert.match(css, /\[data-hnl-brand-panel\] \.bg-blue-600/);
assert.match(app, /getHnlPrimaryThemeColors\(superAdminUiSettings.primaryColor\)/);
assert.match(nav, /data-hnl-nav-surface="mobile"/);
assert.match(nav, /data-hnl-nav-surface="desktop"/);
assert.match(admin, /data-hnl-brand-panel/);
assert.match(home, /data-hnl-home-primary-action/);
assert.match(settings, /data-hnl-settings-surface/);
assert.match(css, /\.bg-rose-50/);
assert.match(css, /\.bg-emerald-50/);
assert.match(css, /\.bg-amber-50/);
// Deep-sheet brand/action regression: do not globally recolor semantic blue data/status.
const warehouse = fs.readFileSync(new URL('src/components/WarehouseTab.tsx', base), 'utf8');
const crew = fs.readFileSync(new URL('src/components/CrewTabBase.tsx', base), 'utf8');
const security = fs.readFileSync(new URL('src/components/SecurityModal.tsx', base), 'utf8');
const floorPlan = fs.readFileSync(new URL('src/components/FloorPlanDefectTab.tsx', base), 'utf8');
assert.match(css, /\[data-hnl-primary-action\] \{ background-color: var\(--hnl-primary-action\)/);
assert.match(css, /\[data-hnl-nested-nav\] \.text-blue-700/);
assert.match(warehouse, /data-hnl-primary-action="warehouse-create"/);
assert.match(warehouse, /data-hnl-primary-action="warehouse-equipment-create"/);
assert.match(warehouse, /data-hnl-nested-nav="warehouse-catalog"/);
assert.match(crew, /data-hnl-primary-action="crew-record-create"/);
assert.match(security, /data-hnl-primary-action="security-sign-in"/);
assert.match(admin, /data-hnl-primary-action="superadmin-ui-save"/);
assert.match(floorPlan, /drawTool === 'freehand'\s*\? 'bg-indigo-600/);
assert.match(floorPlan, /drawTool === 'polygon'\s*\? 'bg-indigo-600/);
assert.match(floorPlan, /drawTool === '2point'\s*\? 'bg-indigo-600/);
assert.match(floorPlan, /isRoomPinPlacementMode\s*\? 'bg-indigo-600/);
// Defect action remains semantic rose, and selected/highlight strokes must not change.
assert.match(floorPlan, /bg-rose-600 hover:bg-rose-700/);
assert.match(floorPlan, /stroke="#f59e0b"/);
assert.match(warehouse, /bg-sky-100/);
assert.match(security, /bg-rose-100 text-rose-700/);
// Copy only: no false "100% saved" when Google authentication URL is missing.
assert.doesNotMatch(settings, /lưu 100% tự động/i);
assert.match(settings, /Không nhận được liên kết đăng nhập Google Drive/);
assert.match(admin, /Áp dụng và lưu/);
assert.match(security, /Khóa PIN/);
assert.match(security, /Phân quyền/);
console.log('HNL NESTED BRAND + VIETNAMESE COPY GOLDEN: PASS');
console.log('HNL PRIMARY COLOR SOURCE GOLDEN: PASS');
