from pathlib import Path

EXPECTED_BASE = 'bd0f2db884e294eee173e1530516ac80ad8800aa'
LEGACY_NAME = 'Trần Thạch Cao Khung Chìm Tấm Tiêu Chuẩn'

# 1) Material Need: require proof that every contributing category still exists in active WorkVolume catalog.
engine_path = Path('src/utils/materialNeedEngine.ts')
engine = engine_path.read_text(encoding='utf-8')
old = """      // An explicit category ID that no longer exists in the active WorkVolume catalog is an orphan linkage.\n      // Do not turn a deleted category into a false MISSING_NORM warning; Health Center owns the orphan audit.\n      if (cat.id && !workVolumes.some((work) => work.id === cat.id || work.workCategoryId === cat.id)) return;\n      const categoryRef = cat.id || cat.name;\n"""
new = """      // Every live material contribution must be provably linked to an ACTIVE WorkVolume.\n      // Explicit legacy IDs are authoritative: never fall back by name when an old ID is gone,\n      // because a newly-created category may later reuse the same display title. Title matching is\n      // allowed only for legacy rows that genuinely have no category ID.\n      const activeWork = cat.id ? resolveWorkVolume(cat.id, workVolumes) : resolveWorkVolume(cat.name, workVolumes);\n      if (!activeWork) return;\n      const categoryRef = cat.id || cat.name;\n"""
assert engine.count(old) == 1, f'material orphan guard anchor count={engine.count(old)}'
engine = engine.replace(old, new, 1)
engine_path.write_text(engine, encoding='utf-8')

# 2) Health Center: surface stale room/category references instead of asking for a new norm.
health_path = Path('src/healthCenter/healthCenterEngine.ts')
health = health_path.read_text(encoding='utf-8')
anchor = """function lightweightBusinessQualityIssues(snapshot: HnlAiProjectSnapshot): HealthCenterIssue[] {\n  const issues: HealthCenterIssue[] = [];\n  const activeWorkVolumeIds = new Set(active(snapshot.workVolumes).flatMap((item) => [item.id, item.workCategoryId].filter(Boolean) as string[]));\n"""
insert = """function lightweightBusinessQualityIssues(snapshot: HnlAiProjectSnapshot): HealthCenterIssue[] {\n  const issues: HealthCenterIssue[] = [];\n  const activeWorkVolumes = active(snapshot.workVolumes);\n  const activeWorkVolumeIds = new Set(activeWorkVolumes.flatMap((item) => [item.id, item.workCategoryId].filter(Boolean) as string[]));\n  const activeWorkVolumeNames = new Set(activeWorkVolumes.map((item) => normalizeEntityText(item.title)).filter(Boolean));\n  const isKnownWorkCategory = (workCategoryId?: string, workCategoryName?: string): boolean => {\n    const id = String(workCategoryId || '').trim();\n    if (id) return activeWorkVolumeIds.has(id);\n    const name = normalizeEntityText(String(workCategoryName || ''));\n    return !name || activeWorkVolumeNames.has(name);\n  };\n\n  active(snapshot.rooms).forEach((room) => {\n    const orphanRefs = new Map<string, { source: string; workCategoryId?: string; workCategoryName?: string }>();\n    const addOrphan = (source: string, workCategoryId?: string, workCategoryName?: string) => {\n      const id = String(workCategoryId || '').trim();\n      const name = String(workCategoryName || '').trim();\n      if ((!id && !name) || isKnownWorkCategory(id, name)) return;\n      const key = id ? `id:${id}` : `name:${normalizeEntityText(name)}`;\n      if (!orphanRefs.has(key)) orphanRefs.set(key, { source, workCategoryId: id || undefined, workCategoryName: name || undefined });\n    };\n\n    if ((Number(room.workVolume) || 0) > 0) addOrphan('room', room.workCategoryId, room.workCategory);\n    Object.entries(room.categoryVolumes || {}).forEach(([raw, volume]) => {\n      if ((Number(volume) || 0) <= 0) return;\n      const rawId = activeWorkVolumeIds.has(raw) ? raw : '';\n      addOrphan('categoryVolumes', rawId, rawId ? '' : raw);\n    });\n    (room.subItems || []).forEach((sub) => {\n      if (sub.workCategoryId) addOrphan('subItem', sub.workCategoryId, sub.category);\n      else if ((Number(sub.workVolume) || 0) > 0) addOrphan('subItem', undefined, sub.category);\n    });\n\n    if (orphanRefs.size > 0) {\n      const refs = Array.from(orphanRefs.values());\n      const labels = refs.map((ref) => ref.workCategoryName || ref.workCategoryId || 'Hạng mục không xác định');\n      issues.push(makeIssue({\n        ruleId: 'ROOM_ORPHAN_WORK_CATEGORY_REFERENCE', severity: 'WARNING', module: 'links', entityType: 'room', entityId: room.id,\n        message: `${room.roomName} còn tham chiếu hạng mục đã xoá/không còn tồn tại: ${labels.join(', ')}. Không dùng tham chiếu này để tính vật tư.`,\n        actionClass: 'NEEDS_CONFIRMATION', evidenceIds: [`rooms:${room.id}`],\n        location: { floorId: room.floorId, floorName: room.floorName, roomId: room.id, roomName: room.roomName, workItem: labels[0] },\n        details: { roomId: room.id, orphanWorkCategoryRefs: refs },\n      }));\n    }\n  });\n"""
assert health.count(anchor) == 1, f'health lightweight anchor count={health.count(anchor)}'
health = health.replace(anchor, insert, 1)
health_path.write_text(health, encoding='utf-8')

# 3) Material Need golden: explicit deleted ID + title-only deleted legacy reference + active title-only compatibility.
mat_test_path = Path('scripts/material-need-golden.ts')
mat_test = mat_test_path.read_text(encoding='utf-8')
anchor = """assert.equal(deletedWorkCategory.lines.length, 0, 'Room reference to a deleted explicit work-category ID must not generate demand');\nassert.equal(deletedWorkCategory.warnings.some((w) => w.code === 'MISSING_NORM'), false, 'Deleted/orphan category must not be misreported as a missing material norm');\n\n\nconst floor1TeamARoom = {\n"""
insert = f"""assert.equal(deletedWorkCategory.lines.length, 0, 'Room reference to a deleted explicit work-category ID must not generate demand');\nassert.equal(deletedWorkCategory.warnings.some((w) => w.code === 'MISSING_NORM'), false, 'Deleted/orphan category must not be misreported as a missing material norm');\n\n// Live-data regression: very old rooms may retain only the deleted category DISPLAY NAME,\n// with no workCategoryId. Such a name must not resurrect a deleted category or create MISSING_NORM.\nconst deletedLegacyTitle = '{LEGACY_NAME}';\nconst deletedLegacyTitleRoom = {{\n  ...multiTeamRoom,\n  id: 'room-deleted-title-only',\n  roomName: 'Legacy deleted title',\n  workCategoryId: undefined,\n  workCategory: '',\n  workVolume: 0,\n  categoryVolumes: {{ [deletedLegacyTitle]: 80 }},\n  categoryVolumeUnits: {{ [deletedLegacyTitle]: 'm²' }},\n  subItems: [],\n}} as RoomProgressItem;\nconst deletedLegacyTitleResult = computeMaterialNeeds({{\n  rooms: [deletedLegacyTitleRoom], materialNorms: [norm], inventory: [], workVolumes, teams, scope: {{ floorId: 'floor-3' }},\n}});\nassert.equal(deletedLegacyTitleResult.lines.length, 0, 'Title-only reference to a deleted category must not generate material demand');\nassert.equal(deletedLegacyTitleResult.warnings.some((w) => w.code === 'MISSING_NORM'), false, 'Deleted title-only category must not be reported as a missing norm');\n\n// Backwards compatibility: title-only legacy rows still calculate when that exact category is ACTIVE.\nconst activeLegacyTitleRoom = {{\n  ...multiTeamRoom,\n  id: 'room-active-title-only',\n  roomName: 'Legacy active title',\n  workCategoryId: undefined,\n  workCategory: '',\n  workVolume: 0,\n  categoryVolumes: {{ 'Trần thạch cao': 40 }},\n  categoryVolumeUnits: {{ 'Trần thạch cao': 'm²' }},\n  subItems: [],\n}} as RoomProgressItem;\nconst activeLegacyTitleResult = computeMaterialNeeds({{\n  rooms: [activeLegacyTitleRoom], materialNorms: [norm], inventory: [], workVolumes, teams, scope: {{ floorId: 'floor-3' }},\n}});\nassert.equal(activeLegacyTitleResult.lines[0]?.estimatedQty, 14, 'Title-only legacy reference must remain supported when exact category is active');\nassert.equal(activeLegacyTitleResult.warnings.some((w) => w.code === 'MISSING_NORM'), false);\n\n\nconst floor1TeamARoom = {{\n"""
assert mat_test.count(anchor) == 1, f'material golden anchor count={mat_test.count(anchor)}'
mat_test = mat_test.replace(anchor, insert, 1)
mat_test_path.write_text(mat_test, encoding='utf-8')

# 4) Health Center orphan golden: the same deleted title must be surfaced as an orphan room reference.
hc_test_path = Path('scripts/health-center-orphan-golden.ts')
hc_test = hc_test_path.read_text(encoding='utf-8')
room_anchor = """  {\n    id: 'room-orphan-team', floorId: 'floor-ok', floorName: 'Tầng hợp lệ', roomName: 'A103',\n    x: 50, y: 0, width: 20, height: 20,\n    frameStatus: 'Chưa làm', boardStatus: 'Chưa làm', inspectionStatus: 'Chưa nghiệm thu', updatedAt: 1,\n    teamId: 'team-missing', assignedTeam: 'Đội đã mất',\n    subItems: [{ id: 'sub-orphan-team', name: 'Khung', status: 'Chưa làm', teamId: 'team-missing-2', assignedTeam: 'Đội đã mất 2' }],\n  },\n];\n"""
room_insert = f"""  {{\n    id: 'room-orphan-team', floorId: 'floor-ok', floorName: 'Tầng hợp lệ', roomName: 'A103',\n    x: 50, y: 0, width: 20, height: 20,\n    frameStatus: 'Chưa làm', boardStatus: 'Chưa làm', inspectionStatus: 'Chưa nghiệm thu', updatedAt: 1,\n    teamId: 'team-missing', assignedTeam: 'Đội đã mất',\n    subItems: [{{ id: 'sub-orphan-team', name: 'Khung', status: 'Chưa làm', teamId: 'team-missing-2', assignedTeam: 'Đội đã mất 2' }}],\n  }},\n  {{\n    id: 'room-orphan-work-title', floorId: 'floor-ok', floorName: 'Tầng hợp lệ', roomName: 'A104',\n    x: 75, y: 0, width: 20, height: 20,\n    frameStatus: 'Chưa làm', boardStatus: 'Chưa làm', inspectionStatus: 'Chưa nghiệm thu', updatedAt: 1,\n    categoryVolumes: {{ '{LEGACY_NAME}': 25 }},\n    categoryVolumeUnits: {{ '{LEGACY_NAME}': 'm²' }},\n  }},\n];\n"""
assert hc_test.count(room_anchor) == 1, f'health orphan room anchor count={hc_test.count(room_anchor)}'
hc_test = hc_test.replace(room_anchor, room_insert, 1)
rule_anchor = """  'MATERIAL_NORM_WORK_CATEGORY_NOT_FOUND',\n  'CHECKLIST_FLOOR_NOT_FOUND',\n"""
rule_insert = """  'MATERIAL_NORM_WORK_CATEGORY_NOT_FOUND',\n  'ROOM_ORPHAN_WORK_CATEGORY_REFERENCE',\n  'CHECKLIST_FLOOR_NOT_FOUND',\n"""
assert hc_test.count(rule_anchor) == 1, f'health orphan rule anchor count={hc_test.count(rule_anchor)}'
hc_test = hc_test.replace(rule_anchor, rule_insert, 1)
assert_anchor = """assert.equal(inventory[0].sourceNormId, 'norm-missing');\n\nconsole.log('Health Center orphan-link golden regression PASS', {\n"""
assert_insert = f"""assert.equal(inventory[0].sourceNormId, 'norm-missing');\nconst orphanWorkIssue = report.issues.find((issue) => issue.ruleId === 'ROOM_ORPHAN_WORK_CATEGORY_REFERENCE' && issue.entityId === 'room-orphan-work-title');\nassert.ok(orphanWorkIssue, 'Health Center must surface title-only deleted work-category references');\nassert.match(orphanWorkIssue!.message, /{LEGACY_NAME}/);\nassert.equal(orphanWorkIssue!.actionClass, 'NEEDS_CONFIRMATION', 'Deleted work-category refs must never auto-repair/relink');\n\nconsole.log('Health Center orphan-link golden regression PASS', {{\n"""
assert hc_test.count(assert_anchor) == 1, f'health orphan assert anchor count={hc_test.count(assert_anchor)}'
hc_test = hc_test.replace(assert_anchor, assert_insert, 1)
hc_test_path.write_text(hc_test, encoding='utf-8')

print('Orphan work-category regression patch applied')
