import assert from 'node:assert/strict';
import fs from 'node:fs';

const quick = fs.readFileSync('src/components/QuickEditGridModal.tsx', 'utf8');
const dataMenu = fs.readFileSync('src/components/DataManagementMenu.tsx', 'utf8');
const actionMenu = fs.readFileSync('src/components/ActionMenuButton.tsx', 'utf8');
const addSourceMenu = fs.readFileSync('src/components/AddSourceMenu.tsx', 'utf8');
const checklist = fs.readFileSync('src/components/ChecklistTab.tsx', 'utf8');
const floor = fs.readFileSync('src/components/FloorPlanDefectTab.tsx', 'utf8');
const crew = fs.readFileSync('src/components/CrewTabBase.tsx', 'utf8');
const warehouse = fs.readFileSync('src/components/WarehouseTab.tsx', 'utf8');
const volume = fs.readFileSync('src/components/WorkVolumeTab.tsx', 'utf8');
const projectManager = fs.readFileSync('src/components/ProjectManagerModal.tsx', 'utf8');
const materialNormModal = fs.readFileSync('src/components/MaterialNormModal.tsx', 'utf8');
const quickSortBar = fs.readFileSync('src/components/QuickSortBar.tsx', 'utf8');
const catalogTemplatePicker = fs.readFileSync('src/components/CatalogTemplatePickerModal.tsx', 'utf8');
const dxf = fs.readFileSync('src/utils/dxfRoomDetection.ts', 'utf8');
const pdfRoomDetection = fs.readFileSync('src/utils/pdfRoomDetection.ts', 'utf8');

assert.match(quick, /Ctrl\+C \/ Ctrl\+V vùng ô từ Excel/, 'Quick grid must advertise spreadsheet paste');
assert.match(quick, /handlePaste/, 'Quick grid must support multi-cell paste');
assert.match(quick, /dirtyCellKeys/, 'Quick grid edits must remain staged until save');
assert.match(quick, /dirtyCellKeys\.size > 0/, 'Quick grid must preserve local draft across realtime/parent refreshes');
assert.match(quick, /const result = await onSave/, 'Quick grid must wait for the module batch-save result');
assert.match(quick, /result === false/, 'Quick grid must keep the draft dirty when module confirmation is cancelled');
assert.match(quick, /Có thay đổi chưa lưu trong Bảng chỉnh nhanh/, 'Quick grid close must guard unsaved local draft');
assert.match(quick, /Có thay đổi chưa lưu trong bảng hiện tại/, 'Quick grid tab switch must guard unsaved local draft');
assert.match(quick, /Bỏ thay đổi/, 'Quick grid must support discard');
assert.match(quick, /Hoàn tác/, 'Quick grid must support undo');
assert.match(quick, /tabs && tabs\.length/, 'Quick grid must support module-specific table tabs');
assert.match(quick, /tăng dần → giảm dần → thứ tự ban đầu/, 'Quick grid headers must use tri-state display sorting');
assert.match(quick, /\+ Trên/, 'Quick grid must support inserting rows above an anchor');
assert.match(quick, /\+ Dưới/, 'Quick grid must support inserting rows below an anchor');
assert.match(quick, /deletedRows/, 'Quick grid must stage row deletions until Save');
assert.match(quick, /canDeleteRows/, 'Quick grid must expose module-controlled multi-row deletion');
assert.match(quick, /syncGroupColumns/, 'Quick grid must support synchronized shared fields for grouped rows');
assert.match(quick, /sticky top-0 left-0 z-50/, 'Quick grid select-all corner must be pinned on both axes');
assert.match(quick, /sticky top-0 z-30 bg-slate-200/, 'Each Quick Edit header cell must own vertical sticky positioning');
assert.doesNotMatch(quick, /<thead className="sticky top-0/, 'Quick Edit must avoid nested sticky thead/header composition that makes the checkbox drift');
assert.match(quick, /allowExpression/, 'Quick grid must support safe arithmetic expressions in numeric cells');
assert.match(quick, /evaluateMathExpression/, 'Quick grid must validate expression-backed numeric cells by numeric result');

assert.match(dataMenu, /Xuất Excel để chỉnh sửa/, 'Data Management menu must be editing-oriented');
assert.match(dataMenu, /Nhập Excel đã chỉnh sửa/, 'Data Management menu must contain round-trip import');
assert.match(dataMenu, /Tải Excel mẫu/, 'Data Management menu must contain template action');
assert.match(fs.readFileSync('src/utils/excelExport.ts', 'utf8'), /XLSX\.utils\.aoa_to_sheet\(\[workVolumeHeaders\]\)/, 'WorkVolume blank template must retain editable headers');
assert.match(fs.readFileSync('src/utils/excelExport.ts', 'utf8'), /XLSX\.utils\.aoa_to_sheet\(\[mainHeaders\]\)/, 'Crew blank template must retain journal headers');
assert.match(fs.readFileSync('src/utils/excelExport.ts', 'utf8'), /'__itemKind': item\.itemKind === 'equipment'/, 'Warehouse inbound round-trip must preserve material-vs-equipment identity');
assert.match(fs.readFileSync('src/utils/excelExport.ts', 'utf8'), /XLSX\.utils\.aoa_to_sheet\(\[inHeaders\]\)/, 'Warehouse blank inbound template must retain headers');
assert.match(dataMenu, /if \(onExportReport\)/, 'Data Management report section must render only when a module explicitly supplies a report callback');
assert.match(dataMenu, /fillMobile/, 'Data Management trigger must support equal-width mobile action rows');
assert.match(dataMenu, /fillWidth/, 'Data Management trigger must support equal-width desktop/mobile action pairs');
assert.match(dataMenu, /onExportReport/, 'Data Management menu must support an optional report action without duplicating standalone buttons');
assert.match(actionMenu, /sm:w-auto/, 'Shared action trigger must be able to fill one mobile grid column without affecting desktop');
assert.match(actionMenu, /whitespace-nowrap/, 'Shared action trigger must keep its compact label intact on mobile');
assert.match(dataMenu, /FileSpreadsheet/, 'Data Management export must retain the spreadsheet icon');
assert.match(dataMenu, /Database/, 'Data Management trigger must use a data icon');
assert.match(dataMenu, /onQuickEdit/, 'Shared Data Management menu must support the Quick Edit action');
assert.match(dataMenu, /Quản lý dữ liệu/, 'Shared Data Management menu must expose the approved data-management label');
assert.match(dataMenu, /triggerTone="secondary"/, 'Data Management trigger must remain visually secondary because it is a lower-frequency action');
assert.match(dataMenu, /mobileLabel="Dữ liệu"/, 'Data Management must use the compact Dữ liệu label on mobile while retaining its full desktop label');
assert.match(actionMenu, /mobileLabel\?: string/, 'Shared action menu must support a shorter mobile label without changing its desktop wording');
assert.match(quickSortBar, /sm:hidden[\s\S]*<select/, 'Quick Sort must collapse to one compact select on mobile');
assert.match(quickSortBar, /hidden sm:block[\s\S]*Sắp xếp nhanh:/, 'Quick Sort must retain the visible chip bar on tablet\/desktop');
assert.match(materialNormModal, /expandedNormTagIds/, 'Material Norm cards must support expanding hidden work-category tags on mobile');
assert.match(materialNormModal, /sm:hidden inline-flex[\s\S]*\+\$\{hiddenCount\}/, 'Material Norm cards must collapse extra mobile tags behind a +N control');
assert.match(actionMenu, /border-slate-200 bg-white text-slate-600 shadow-none/, 'Shared action menu must support a quiet secondary trigger style');
assert.match(actionMenu, /placement: 'above' \| 'below'/, 'Shared action menu must support opening above or below the pressed trigger');
assert.match(actionMenu, /scrollTopBeforeOpenRef/, 'Opening a shared action menu must preserve the page scroll position');
assert.match(addSourceMenu, /Chọn cách thêm/, 'Shared Add Source menu must expose one consistent source-choice pattern');
assert.match(addSourceMenu, /Tạo mới để nhập thủ công/, 'Shared Add Source menu must explain create-vs-copy behavior');
assert.match(actionMenu, /data-hnl-action-menu-mode/, 'Shared action menu must expose its adaptive runtime mode');
assert.match(actionMenu, /naturalHeight > bestAvailable && naturalHeight > 220/, 'Shared action menu must use bottom sheet only when a longer mobile menu cannot fit near the trigger');
assert.match(checklist, /<DataManagementMenu/, 'Checklist must use shared Data Management instead of standalone Excel buttons');
for (const [name, source] of [['floor', floor], ['crew', crew], ['warehouse', warehouse], ['volume', volume]] as const) {
  assert.match(source, /quickEditEnabled\?: boolean;/, `${name} must expose a Quick Edit runtime enable flag`);
  assert.match(source, /import\('\.\/QuickEditGridModal'\)/, `${name} must lazy-load Quick Edit instead of parsing the grid with the heavy tab chunk`);
  assert.doesNotMatch(source, /import \{ QuickEditGridModal,/, `${name} must not statically import the Quick Edit runtime component`);
  assert.match(source, /quickEditEnabled && showQuickEdit/, `${name} must not mount Quick Edit while disabled or closed`);
}

assert.match(floor, /Căn & Hạng mục/, 'Floor quick edit must separate room/work rows');
assert.match(floor, /Deadline defect/, 'Defect quick edit must expose deadline');
assert.match(floor, /Ngày hoàn thành thực tế defect/, 'Defect quick edit must expose actual completion date');
assert.match(floor, /__floorId/, 'Multi-floor Excel must keep durable floor ID');
assert.match(floor, /multiFloorImport/, 'Room Excel import must support multi-floor input');
assert.match(floor, /không được tự đổi floorId qua Excel/, 'Excel import must fail closed on cross-floor identity mismatch');
assert.match(floor, /__recordId không tồn tại trong dự án hiện tại/, 'Room Excel import must reject stale technical room IDs instead of falling back to names');
assert.match(floor, /onApplyRoomExcelImport\(preparedRooms, obsoleteRoomIds\)/, 'Room Excel import must preflight every row then apply one atomic App-state transaction');
assert.match(floor, /__subItemId không tồn tại/, 'Room detail Excel import must reject stale technical sub-item IDs');
assert.match(floor, /PDF\/JPG\/PNG\/WebP\/DXF/, 'Add-floor drawing picker must include DXF beside PDF/images');
assert.match(floor, /createFloor: true/, 'DXF selected from add-floor flow must create the requested new floor only after review');
assert.doesNotMatch(floor, /<FileType[^>]*\/> Nhận diện CAD\/DXF/, 'Room toolbar must not expose a separate CAD/DXF button');
assert.match(floor, /Chỉ tạo tầng/, 'DXF review must let the user create the floor without auto-creating rooms');
assert.match(floor, /Tạo tầng \+ Căn \/ Phòng/, 'DXF review must support creating the floor and detected rooms together');
assert.match(floor, /isPolyline: false,/, 'DXF closed room boundaries must persist as polygon geometry for fill and Defect hit-testing');
assert.match(floor, /Tự động · Khuyên dùng/, 'Smart PDF must present the default room-name rule in user-friendly language');
assert.match(floor, /Tùy chỉnh kỹ thuật \(Regex\)/, 'Raw Smart PDF regex must stay behind an explicit technical disclosure');
assert.match(floor, /Không cần nhập ký tự kỹ thuật/, 'Normal Smart PDF UI must tell users that technical syntax is not required');
assert.match(floor, /Khôi phục mặc định/, 'Advanced PDF name regex must provide a safe reset action');
assert.match(floor, /aria-invalid=\{!isSmartPdfNamePatternValid\}/, 'Advanced PDF name regex must surface invalid syntax before detection');
assert.doesNotMatch(pdfRoomDetection, /\(\?=\.\*/, 'Default room-name regex should avoid the hard-to-read lookahead form reported on mobile');
assert.match(floor, /Tạo Căn \/ Phòng từ DXF/, 'DXF import must retain an explicit review/apply path');
assert.match(floor, /Không ghi đè Căn \/ Phòng đã tồn tại/, 'DXF import must protect existing room highlights');
assert.match(floor, /Lấy mặt bằng trực tiếp từ DXF/, 'DXF review must offer CAD-background materialization');
assert.match(floor, /cadSource:/, 'Saved DXF room highlights must retain immutable CAD geometry for later alignment');
assert.match(volume, /floorId: undefined[\s\S]{0,120}floorIds: targetFloorIds[\s\S]{0,120}floor: GLOBAL_WORK_SCOPE_LABEL/, 'Cross-project Work Volume copy must drop source floor identity and remain global until the target project scopes it explicitly');
assert.doesNotMatch(volume, /const fallbackFloor = floorPlans\[0\]/, 'Cross-project Work Volume copy must not silently bind the imported catalog to the first target floor');
assert.doesNotMatch(volume, /floorNamesById/, 'Cross-project Work Volume copy must not depend on non-schema source floor-name metadata');
assert.match(materialNormModal, /uniqueByCanonicalId\.length !== 1/, 'Material Norm remap must fail closed when a target Work Category title is missing or ambiguous');
assert.match(materialNormModal, /trùng tên/, 'Material Norm remap must explain ambiguous target Work Category names instead of choosing one silently');
assert.match(materialNormModal, /inputExpressions/, 'Material Norm editor must retain general/specific arithmetic expressions');
assert.match(floor, /syncGroupColumns=\{quickEditMode === 'rooms'/, 'Room quick edit must synchronize shared room fields across child rows');
assert.match(floor, /sm:grid-cols-\[minmax\(0,1fr\)_auto\][\s\S]*sm:grid-flow-col[\s\S]*Quản lý Khu\/Khối & Tầng[\s\S]*triggerLabel="Quản lý dữ liệu"[\s\S]*onQuickEdit/, 'Floor actions must sit horizontally to the right of the current-view context and combine Quick Edit + Excel');
const acceptanceSection = floor.slice(floor.indexOf('Nghiệm thu từng Căn / Phòng'), floor.indexOf('Quick Sort Controls'));
assert.doesNotMatch(acceptanceSection, /Thêm Căn \/ Phòng/, 'Acceptance section must not duplicate the add-room action');
assert.doesNotMatch(acceptanceSection, /Bảng chỉnh nhanh/, 'Acceptance section must not duplicate bulk-edit actions');


assert.match(floor, /__floorPrimary/, 'Floor quick edit must expose exactly one canonical editable row per floor');
assert.match(floor, /floorEditById/, 'Floor quick edit must stage floor-level edits separately from room edits');
assert.match(floor, /onRenameFloorPlan\(floorId, edit\.floorName\)/, 'Floor quick edit must rename through the existing cascade-safe floor handler');
assert.match(floor, /onUpdateFloorPlan\(floorId, \{ structureGroupId: edit\.structureGroupId \}\)/, 'Floor quick edit must update Khu/Khối by stable structureGroupId');
assert.match(floor, /triggerLabel="Quản lý dữ liệu"/, 'Floor Quick Edit + Excel must be consolidated under Quản lý dữ liệu');

assert.match(crew, /Xuất Nhật ký để chỉnh sửa/, 'Crew must export journal for editing');
assert.match(crew, /Nhập Nhật ký đã chỉnh sửa/, 'Crew must import edited journal');
assert.match(crew, /chi tiet cong viec/i, 'Crew import must understand detailed work sheet');
assert.match(crew, /__teamId không tồn tại trong dự án hiện tại/, 'Crew Excel import must reject stale technical team IDs');
assert.match(crew, /__recordId không tồn tại trong dự án hiện tại/, 'Crew Excel import must reject stale journal IDs');
assert.match(crew, /onExportReport=\{\(\) => handleExportTeamStats\(\)\}/, 'All-team statistics export must live inside the team Excel menu');
assert.match(crew, /reportLabel="Thống kê tất cả đội"/, 'Team Excel menu must label the all-team report clearly');
assert.doesNotMatch(crew, /bg-emerald-600[\s\S]{0,220}Thống kê tất cả đội/, 'All-team statistics must not remain as a standalone toolbar button');
assert.match(crew, /Xuất Excel Đội Này/, 'Single-team report export must remain available');
assert.match(crew, /grid grid-cols-2 gap-2 sm:flex sm:items-center sm:justify-between/, 'Team-detail footer must use two balanced mobile columns');
assert.match(crew, /sm:hidden">Xuất Excel</, 'Team-detail Excel action must use a compact mobile label');
assert.match(crew, /sm:hidden">Đóng</, 'Team-detail close action must use a compact mobile label');
assert.match(crew, /w-full sm:w-auto min-h-10 bg-emerald-600/, 'Team-detail Excel action must fill its mobile column');
assert.match(crew, /selectedLogStructureGroupId/, 'Crew entry must expose an explicit Khu/Khối selection state');
assert.match(crew, /Danh sách Tầng bên dưới chỉ hiện trong/, 'Crew entry must explain that floor choices are filtered by Khu/Khối');
assert.match(crew, /key: 'structureGroup'/, 'Crew quick edit must include a Khu/Khối column');
assert.match(crew, /__groupPrimary: floorIndex === 0 && categoryIndex === 0/, 'Crew quick edit must use one representative row for shared journal fields');
assert.match(crew, /syncGroupColumns=\{quickEditMode === 'logs'/, 'Crew child rows must stay synchronized with representative shift/date/team values');
assert.match(crew, /Tầng không thuộc Khu\/Khối này/, 'Crew quick edit must reject floor/group mismatches');
assert.match(crew, /order-1 col-span-2 lg:order-none lg:col-span-1[\s\S]*aria-label="Chọn ngày quân số"[\s\S]*order-2 col-span-2[\s\S]*Ghi nhận quân số/, 'Crew mobile must show Date first, then the highlighted full-width Record action');
assert.match(crew, /order-5 col-span-2 lg:order-none lg:col-span-1[\s\S]*triggerLabel="Quản lý dữ liệu"/, 'Crew mobile Data Management action must occupy a full row while PC stays one toolbar column');
assert.match(crew, /lg:grid-cols-\[220px_minmax\(0,1fr\)_minmax\(0,1fr\)_minmax\(0,1\.1fr\)_minmax\(0,1fr\)\][\s\S]*Chia sẻ báo cáo quân số[\s\S]*triggerLabel="Quản lý dữ liệu"/, 'Crew PC must preserve Date, Record, Copy, Share and Data Management on one aligned row');
assert.doesNotMatch(crew, /crew-subtab-navigation[^\n]*lg:max-w/, 'Crew primary subtabs must remain full-width like the original layout');
assert.match(crew, /triggerLabel="Quản lý dữ liệu"[\s\S]*onQuickEdit=\{quickEditEnabled \? \(\(\) => \{ setQuickEditMode\('teams'\); setShowQuickEdit\(true\); \}\) : undefined\}[\s\S]*reportLabel="Thống kê tất cả đội"/, 'Team directory must consolidate Quick Edit and Excel under the same data menu');

assert.match(warehouse, /Định mức theo Hạng mục/, 'Warehouse quick edit must expose the safe per-work-category norm table');
assert.match(warehouse, /Nhập kho/, 'Warehouse quick edit must have inbound ledger table');
assert.match(warehouse, /Xuất kho/, 'Warehouse quick edit must have outbound ledger table');
assert.match(warehouse, /Tồn kho 🔒/, 'Warehouse stock must be visibly read-only');
assert.match(warehouse, /quickEditMode === 'stock' \? false/, 'Stock quick table must reject edits');
assert.match(warehouse, /Mã Phiếu không tồn tại trong dự án hiện tại/, 'Warehouse Excel import must reject stale transaction IDs');
assert.match(warehouse, /assertKnownReference/, 'Warehouse Excel import must validate technical linkage IDs before writing');
assert.match(warehouse, /key: 'workCategory'[\s\S]*type: 'select'[\s\S]*options: warehouseWorkOptions/, 'Warehouse norm quick edit must select work categories from the authoritative catalog');
assert.match(warehouse, /key: 'specificNorm'.*editable: hasNormManageAccess/, 'Warehouse norm quick edit must expose editable per-work-category norm');
assert.match(warehouse, /key: 'materialName'.*__groupPrimary/, 'Only the grouped primary row may edit the shared material name');
assert.match(warehouse, /key: 'category'.*__groupPrimary/, 'Only the grouped primary row may edit the shared material group');
assert.match(warehouse, /key: 'unit'.*__groupPrimary/, 'Only the grouped primary row may edit the shared material unit');
assert.match(warehouse, /key: 'generalNorm'.*__groupPrimary/, 'Only the grouped primary row may edit the shared general norm');
assert.match(warehouse, /Định mức tổng theo KL kế hoạch.*editable: false/, 'Derived material quota must be read-only in Quick Edit');
assert.match(warehouse, /syncGroupColumns=\{quickEditMode === 'norms'/, 'Grouped norm rows must synchronize shared edits across child rows');
assert.match(warehouse, /workCategoryNormsById/, 'Warehouse norm quick edit must persist per-work-category norms in the existing ID map');
assert.match(warehouse, /inputExpressions/, 'Warehouse must persist quantity and norm expressions instead of flattening them to numbers');
assert.match(warehouse, /readExcelFormulaByHeaders/, 'Warehouse Excel import must read real cell formulas for round-trip editing');
assert.match(warehouse, /Không thể đổi ĐVT/, 'Quick norm edit must block unsafe unit changes when warehouse history exists');
assert.match(warehouse, /Không thể xóa Hạng mục cuối cùng/, 'Quick norm edit must protect the final work-category link');
assert.match(warehouse, /requiresAnchorForInsert=\{quickEditMode === 'norms'\}/, 'Norm child insertion must require an existing material anchor');
assert.match(warehouse, /canAddRows=\{quickEditMode === 'norms' \? hasNormManageAccess/, 'Norm quick edit may add child links only under ADMIN material-norm access');
assert.match(warehouse, /order-first col-span-2[\s\S]*Tạo phiếu/, 'Warehouse mobile primary Create Voucher action must occupy a full highlighted row');
assert.match(warehouse, /lg:grid-flow-col[\s\S]*Tạo phiếu[\s\S]*Danh mục kho[\s\S]*triggerLabel="Quản lý dữ liệu"[\s\S]*onQuickEdit/, 'Warehouse PC actions must keep Create Voucher first, then Catalog/Norms, with consolidated data management');

assert.match(volume, /Khối lượng đã làm/, 'WorkVolume quick table must show actual volume');
assert.match(volume, /key: 'actual'.*editable: false/, 'Actual volume must be read-only');
assert.match(volume, /Khu\/Khối tự đồng bộ từ các tầng đã gán/, 'WorkVolume structure scope must derive from floor assignments');
assert.match(volume, /__recordId không tồn tại trong dự án hiện tại/, 'WorkVolume Excel import must reject stale record IDs');
assert.match(volume, /__floorId\/__floorIds không tồn tại/, 'WorkVolume Excel import must reject stale floor IDs');
assert.match(volume, /canDeleteRows=\{hasStructureManageAccess\}/, 'WorkVolume quick edit must allow ADMIN-staged row deletion');
assert.match(volume, /inputExpressions/, 'WorkVolume must retain planned and unit-price expressions');
assert.match(volume, /readExcelFormulaByHeaders/, 'WorkVolume Excel import must round-trip real cell formulas');

assert.match(dxf, /HATCH/, 'DXF detector must support HATCH');
assert.match(dxf, /LWPOLYLINE/, 'DXF detector must support closed polylines');
assert.match(dxf, /MTEXT/, 'DXF detector must support MTEXT');
assert.match(dxf, /areaM2/, 'DXF detector must calculate metric area');
assert.match(dxf, /\$EXTMIN/, 'DXF detector must prefer drawing extents for alignment');
assert.match(dxf, /readHatchBoundaryShapes/, 'DXF detector must parse all HATCH boundary paths, not only the first loop');
assert.match(dxf, /alignedX/, 'DXF TEXT reader must honor justified alignment point 11\/21');
assert.match(dxf, /measurement/, 'DXF room-name selection must de-prioritize area/measurement labels');

assert.match(projectManager, /Tạo từ mẫu công trình/, 'Project creation must expose template-based creation');
assert.match(projectManager, /templateSourceProjectId/, 'Template creation must allow choosing another accessible project as source');
assert.match(projectManager, /workVolumes: templateCopyOptions\.workVolumes \? templateWorkVolumes : \[\]/, 'Template clone must include work-category catalog when selected');
assert.match(projectManager, /materialNorms: templateCopyOptions\.materialNorms/, 'Template clone must include material norms without warehouse transactions');
assert.match(projectManager, /inventory: \[\]/, 'Template clone must never copy warehouse transaction history');
assert.match(projectManager, /saveProjectSharedSettings\(newProjectId, \{ structure: templateSourceStructure \}\)/, 'Template clone must preserve Khu/Khối structure settings');
assert.match(volume, /onOpenSourcePicker=\{\(\) => setShowTemplatePicker\(true\)\}/, 'Work Volume must keep the existing cross-project/template picker behind Add Source');
assert.match(crew, /onOpenSourcePicker=\{\(\) => setShowTeamTemplatePicker\(true\)\}/, 'Team directory must keep the existing cross-project/template picker behind Add Source');
assert.match(materialNormModal, /onOpenSourcePicker=\{\(\) => setShowNormTemplatePicker\(true\)\}/, 'Material Norms must keep the existing cross-project/template picker behind Add Source');
assert.match(catalogTemplatePicker, /Lưu giỏ thành mẫu/, 'Cross-project picker must support saving a reusable personal template');
assert.match(catalogTemplatePicker, /Mẫu đã lưu/, 'Cross-project picker must support loading saved templates');
assert.match(catalogTemplatePicker, /fetchProjectFromCloud\(sourceProjectId, \{ serverOnly: true \}\)/, 'Cross-project picker must server-verify source project data');
assert.match(catalogTemplatePicker, /fetchUserCatalogTemplates/, 'Reusable templates must be read from the signed-in user cloud profile');

console.log('Quick Edit + Excel + DXF Golden: PASS');

assert.match(volume, /grid w-full grid-cols-\[minmax\(0,1fr\)_auto\][\s\S]*<AddSourceMenu[\s\S]*triggerLabel="Thêm hạng mục"[\s\S]*triggerLabel="Quản lý dữ liệu"/, 'Work Volume mobile Add Source and compact Data Management must share one action row');
assert.match(volume, /sm:grid-flow-col[\s\S]*<AddSourceMenu[\s\S]*triggerLabel="Thêm hạng mục"[\s\S]*triggerLabel="Quản lý dữ liệu"[\s\S]*onQuickEdit/, 'Work Volume PC actions must use shared Add Source plus consolidated Data Management');
